// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0LFdN0-IG0uoR6vYaz6jInAg-EOhM5yY',
    appId: '1:825724032753:web:058fc20e3c43513ba13b50',
    messagingSenderId: '825724032753',
    projectId: 'thriftale-shop',
    authDomain: 'thriftale-shop.firebaseapp.com',
    storageBucket: 'thriftale-shop.firebasestorage.app',
    measurementId: 'G-MVEKFLV4KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuekNFwIsXFUBtnX4NY_WGMueIEBv2QN4',
    appId: '1:825724032753:android:c1e358f450e5f592a13b50',
    messagingSenderId: '825724032753',
    projectId: 'thriftale-shop',
    storageBucket: 'thriftale-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhTsIRn4oTFEsX2mYUICqdxKXIEMlOkC4',
    appId: '1:825724032753:ios:ce513fcfb7cd3229a13b50',
    messagingSenderId: '825724032753',
    projectId: 'thriftale-shop',
    storageBucket: 'thriftale-shop.firebasestorage.app',
    iosBundleId: 'com.thriftle.thriftale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhTsIRn4oTFEsX2mYUICqdxKXIEMlOkC4',
    appId: '1:825724032753:ios:ce513fcfb7cd3229a13b50',
    messagingSenderId: '825724032753',
    projectId: 'thriftale-shop',
    storageBucket: 'thriftale-shop.firebasestorage.app',
    iosBundleId: 'com.thriftle.thriftale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0LFdN0-IG0uoR6vYaz6jInAg-EOhM5yY',
    appId: '1:825724032753:web:25fdaf30ab19648da13b50',
    messagingSenderId: '825724032753',
    projectId: 'thriftale-shop',
    authDomain: 'thriftale-shop.firebaseapp.com',
    storageBucket: 'thriftale-shop.firebasestorage.app',
    measurementId: 'G-8MGS0RTYHC',
  );
}
